export const FETCHING_CATEGORY_LIST = 'FETCHING_CATEGORY_LIST'
export const FETCHING_CATEGORY_LIST_SUCCESS = 'FETCHING_CATEGORY_LIST_SUCCESS'
export const FETCHING_CATEGORY_LIST_ERROR = 'FETCHING_CATEGORY_LIST_ERROR'

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'
export const UNSET_SELECTED_CATEGORY = 'UNSET_SELECTED_CATEGORY'
