export const FETCHING_COMMENT_LIST = 'FETCHING_COMMENT_LIST'
export const FETCHING_COMMENT_LIST_SUCCESS = 'FETCHING_COMMENT_LIST_SUCCESS'
export const FETCHING_COMMENT_LIST_ERROR = 'FETCHING_COMMENT_LIST_ERROR'

export const CREATING_COMMENT = 'CREATING_COMMENT'
export const CREATING_COMMENT_SUCCESS = 'CREATING_COMMENT_SUCCESS'
export const CREATING_COMMENT_ERROR = 'CREATING_COMMENT_ERROR'

export const OPEN_EDIT_COMMENT = 'OPEN_EDIT_COMMENT'
export const CLOSE_EDIT_COMMENT = 'CLOSE_EDIT_COMMENT'

export const UPDATING_COMMENT = 'UPDATING_COMMENT'
export const UPDATING_COMMENT_SUCCESS = 'UPDATING_COMMENT_SUCCESS'
export const UPDATING_COMMENT_ERROR = 'UPDATING_COMMENT_ERROR'

export const DELETING_COMMENT = 'DELETING_COMMENT'
export const DELETING_COMMENT_SUCCESS = 'DELETING_COMMENT_SUCCESS'
export const DELETING_COMMENT_ERROR = 'DELETING_COMMENT_ERROR'

export const UP_VOTING_COMMENT = 'UP_VOTING_COMMENT'
export const UP_VOTING_COMMENT_SUCCESS = 'UP_VOTING_COMMENT_SUCCESS'
export const UP_VOTING_COMMENT_ERROR = 'UP_VOTING_COMMENT_ERROR'

export const DOWN_VOTING_COMMENT = 'DOWN_VOTING_COMMENT'
export const DOWN_VOTING_COMMENT_SUCCESS = 'DOWN_VOTING_COMMENT_SUCCESS'
export const DOWN_VOTING_COMMENT_ERROR = 'DOWN_VOTING_COMMENT_ERROR'
