export const FETCHING_POST_LIST = 'FETCHING_POST_LIST'
export const FETCHING_POST_LIST_SUCCESS = 'FETCHING_POST_LIST_SUCCESS'
export const FETCHING_POST_LIST_ERROR = 'FETCHING_POST_LIST_ERROR'

export const SET_FILTERED_POST_CATEGORY = 'SET_FILTERED_POST_CATEGORY'
export const UNSET_FILTERED_POST_CATEGORY = 'UNSET_FILTERED_POST_CATEGORY'

export const SORT_POST_BY_DATE = 'SORT_POST_BY_DATE'
export const SORT_POST_BY_SCORE = 'SORT_POST_BY_SCORE'
export const SORT_POST_BY_COMMENTS = 'SORT_POST_BY_COMMENTS'

export const OPEN_NEW_POST = 'OPEN_NEW_POST'
export const OPEN_EDIT_POST = 'OPEN_EDIT_POST'
export const CLOSE_SET_POST = 'CLOSE_SET_POST'

export const CREATING_POST = 'CREATING_POST'
export const CREATING_POST_SUCCESS = 'CREATING_POST_SUCCESS'
export const CREATING_POST_ERROR = 'CREATING_POST_ERROR'

export const FETCHING_SINGLE_POST = 'FETCHING_SINGLE_POST'
export const FETCHING_SINGLE_POST_SUCCESS = 'FETCHING_SINGLE_POST_SUCCESS'
export const FETCHING_SINGLE_POST_ERROR = 'FETCHING_SINGLE_POST_ERROR'

export const UPDATING_POST = 'UPDATING_POST'
export const UPDATING_POST_SUCCESS = 'UPDATING_POST_SUCCESS'
export const UPDATING_POST_ERROR = 'UPDATING_POST_ERROR'

export const DELETING_POST = 'DELETING_POST'
export const DELETING_POST_SUCCESS = 'DELETING_POST_SUCCESS'
export const DELETING_POST_ERROR = 'DELETING_POST_ERROR'

export const VOTING_UP_POST = 'VOTING_UP_POST'
export const VOTING_UP_POST_SUCCESS = 'VOTING_UP_POST_SUCCESS'
export const VOTING_UP_POST_ERROR = 'VOTING_UP_POST_ERROR'

export const VOTING_DOWN_POST = 'VOTING_DOWN_POST'
export const VOTING_DOWN_POST_SUCCESS = 'VOTING_DOWN_POST_SUCCESS'
export const VOTING_DOWN_POST_ERROR = 'VOTING_DOWN_POST_ERROR'
